name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Set your AWS region

      - name: Terraform companya Init
        run: cd enviroments/companya/ ; terraform init

      - name: Terraform companya Apply  
        run: cd enviroments/companya/ ; echo terraform apply -auto-approve 
  
      - name: Terraform companyb Init
        run: cd enviroments/companyb/ ; terraform init

      - name: Terraform companya Plan  
        run: cd enviroments/companya/ ; terraform plan  
 
      - name: Terraform vpc_peering Init
        run: cd enviroments/vpc_peering  ; terraform init

      - name: Terraform vpc_peering  Plan  
        run: cd enviroments/vpc_peering / ; terraform plan  
 

      - name: Terraform companya Destory  
        run: cd enviroments/companya/ ; echo terraform destroy -auto-approve
  
    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve
